apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector
  labels:
    helm.sh/chart: vector-0.33.0
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: test
    app.kubernetes.io/component: Agent
    app.kubernetes.io/version: "0.38.0-distroless-libc"
    app.kubernetes.io/managed-by: Helm
    
automountServiceAccountToken: true